config/routes.rb
Rails.application.routes.draw do
  get 'techstack/index'
  get 'profiles/show'
  get 'guidelines/index'
  get 'matchtrips/create'
  root to: 'welcome#index'
  resources :users, only: [:show] do 
    resources :profiles, only: [:index]

  end

  resources :drivers, only: [:index, :show] do
    resources :reviews, only: [:create]
  end
  resources :parenttrips, only: [:create, :new, :index, :show] 


  resources :drivertrips, only: [:create, :new]
  
  resources :matchedtrips, only: [:create]
  
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  post '/notifications/notify' => 'notifications#notify'


end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  
  def index
    @drivers = User.all
  end

  def show
    @driver = User.find params[:id]
    @reviews = Review.where(user_id: params[:id])
    @review = Review.new
  end

end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_driver.html.erb
<% @drivers.each do |driver| %>
    <ul class="list-unstyled col-sm driverlist">
        <div class=" driverm">
            <%= link_to driver_path driver do %>
                <img src="<%= driver.user_pic%>" />
            <% end %>
        </div>
        <div class="media-body ">
        <div>
            <p><strong>First Name:</strong> &nbsp; <%= driver.first_name %></p>
            <p><strong>Last Name:</strong> &nbsp; <%= driver.last_name%></p>
            <p><strong>Email:</strong> &nbsp; <%= driver.email%></p>
            <p><strong>Phone:</strong> &nbsp; <%= driver.phone%></p>
        </div>
        </div>
    </ul>

<% end %>

app/views/drivers/index.html.erb
<%= react_component('Navbar', {current_user: current_user}) %>

<div class="container driverc text-center">
    <h2> Driver List</h2>
    <%= render 'driver' %>
</div>

app/views/drivers/show.html.erb
<%= react_component('Navbar', {current_user: current_user}) %>


<div class="container driversh">
    <h2><%= @driver.first_name %>'s Details</h2>
    <div class=" driverm">
        <img src="<%= @driver.user_pic%>" />
    </div>
    <div>
        <p><strong>First Name:</strong> &nbsp; <%= @driver.first_name %></p>
        <p><strong>Last Name:</strong> &nbsp;   <%= @driver.last_name%></p>
        <p><strong>Email:</strong> &nbsp;      <%= @driver.email%></p>
        <p><strong>Phone:</strong> &nbsp;      <%= @driver.phone%></p>
    </div>
    <div>
        <h3>Reviews</h3>
    </div>
    <div class="reviews">
        <% @reviews.each do |review| %>
            <% review.rating.times do  %>
                <i class="fas fa-star"></i>
            <%end %>
        <span> &nbsp; <%= review.comment %></span><br>
        <% end %>
    </div>
        <%= form_for [@driver, @review], url: driver_reviews_path(@driver.id) do |form| %>
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">New Review</span>
                </div>
            <%= form.text_area :comment %>
                            <div class="rating">
                <h3>Ratings</h3>
                <%= form.select :rating, [1, 2, 3, 4, 5] %>
                <%= form.submit "Create" %>
            <% end %>
        </div>
    </div>
</div>